### ISSUE TITLE
URL of Repository

### ISSUE THREAD

**Issue by AlbertHart** [ice6/opensheetmusicdisplay#1]
When I load the ice6/opensheetmusicdisplay in GitHUB Desktop, the button to go to it on thewebsite goes to OSMD instead. Is that a setting in GitHUB that you can change?

![image](https://user-images.githubusercontent.com/8965352/82358331-9d014500-99c3-11ea-9d30-c98b903a1e6c.png)

**Comment by ice6** [comment]
It is stange, I use the latest version of Github Desktop, has no such option :(

![image](https://user-images.githubusercontent.com/889040/82397409-fa100000-9a82-11ea-9b27-62b4ba0156ac.png)

![image](https://user-images.githubusercontent.com/889040/82397433-098f4900-9a83-11ea-868d-fd282a74c559.png)

**Comment by AlbertHart** [comment]
I am going to check foer updates. Perhaps that feature disappeared???

Here is my about display:

![image](https://user-images.githubusercontent.com/8965352/82405831-37907100-9a22-11ea-90e0-8d3d85925645.png)

**Comment by AlbertHart** [comment]
I get this message when I click check ofor updates. I'll try looking at the page they suggest

![image](https://user-images.githubusercontent.com/8965352/82405924-70c8e100-9a22-11ea-9b23-ceb7a75f42b9.png)

**Comment by AlbertHart** [comment]
In moved GitHub Desktop.app to the Applications Folder and got rid of the Check for Update error. and I now have the latest version.

**Comment by AlbertHart** [comment]
This setting seems to be correct. But going to the repository seems to go to the wrong place.

![image](https://user-images.githubusercontent.com/8965352/82406489-03b64b00-9a24-11ea-9335-f1df643806e2.png)

Can you try to load the repository from GitHub Desktop using this menu setting?

![image](https://user-images.githubusercontent.com/8965352/82406550-2c3e4500-9a24-11ea-994f-f69f844260a5.png)

**Comment by ice6** [comment]
It is strange, I can not. The menu Item is gray.

I don't have the `Open the repository page on Github in your browser` option. 

![image](https://user-images.githubusercontent.com/889040/82415292-e4163580-9aaa-11ea-8949-ee8745277c6f.png)
