### ISSUE TITLE
Am I working in a branch.

### ISSUE THREAD

**Issue by AlbertHart** [ice6/opensheetmusicdisplay#5]
I see this when I go to the code tab.

I am surprised that I see only my commits. Are you working in a different fork or branch?

![image](https://user-images.githubusercontent.com/8965352/82406739-a7076000-9a24-11ea-9995-2fdd2199cc15.png)

**Comment by ice6** [comment]
@AlbertHart 

I am working on the `master` branch. Make sure you are working the same branch. Yes, [it](https://github.com/ice6/opensheetmusicdisplay/commits/master) shows your also working on the `master` branch.

the arrows:

1. yes, it is a fork

2. yes, our fork is ahead of opensheetmusicdisplay. Strictly speaking, the fork is indpendant git repo. But the internal structure Github using may be a branch of the original code.

3. when you commit code, maybe there is a auto merge. for example, if you change the README.md file in the browser, it would make the git tree forword. When you commit your code from GitHub Desktop, it detected that there is no conflict about the changes, then a auto merge happeded.
